'use client';
import Link from 'next/link'; import {useEffect,useState} from 'react';
const quick=[['📖','القرآن الكريم','/quran'],['🎧','التلاوات','/audio'],['📚','الأحاديث','/hadith'],['🤲','الأذكار','/adhkar'],['🕋','القبلة','/qibla'],['🕌','الصلاة','/prayer'],['🌙','رمضان','/ramadan'],['✨','أسماء الله','/names'],['🌿','وردك اليوم','/daily']];
export default function Home(){
 const [p,setP]=useState<any>(); const [q,setQ]=useState(''); const [h,setH]=useState<any>(); const [now,setNow]=useState(new Date());
 const [coords,setCoords]=useState({lat:30.0444,lon:31.2357});
 useEffect(()=>{if(navigator.geolocation) navigator.geolocation.getCurrentPosition(x=>setCoords({lat:x.coords.latitude,lon:x.coords.longitude}),()=>{});},[]);
 useEffect(()=>{fetch(`/api/prayer?lat=${coords.lat}&lon=${coords.lon}&method=5`).then(r=>r.json()).then(setP).catch(()=>{});fetch('/api/hadith').then(r=>r.json()).then(d=>setH(d.items?.[0])).catch(()=>{})},[coords.lat,coords.lon]);
 useEffect(()=>{const t=setInterval(()=>setNow(new Date()),1000);return()=>clearInterval(t)},[]);
 const prayers=[['الفجر','Fajr'],['الشروق','Sunrise'],['الظهر','Dhuhr'],['العصر','Asr'],['المغرب','Maghrib'],['العشاء','Isha']];
 const parse=(v:string)=>{if(!v)return null;const clean=v.split(' ')[0];const [hh,mm]=clean.split(':').map(Number);const d=new Date(now);d.setHours(hh,mm,0,0);return d};
 const upcoming=prayers.map(([a,b])=>({name:a,key:b,time:p?.timings?.[b],date:parse(p?.timings?.[b])})).filter(x=>x.date).find(x=>x.date!>now) || (()=>{const x=prayers.map(([a,b])=>({name:a,key:b,time:p?.timings?.[b],date:parse(p?.timings?.[b])})).find(y=>y.date);if(x?.date)x.date.setDate(x.date.getDate()+1);return x})();
 const diff=upcoming?.date?Math.max(0,upcoming.date.getTime()-now.getTime()):0; const hrs=Math.floor(diff/3600000), mins=Math.floor((diff%3600000)/60000), secs=Math.floor((diff%60000)/1000);
 const fmt=(n:number)=>String(n).padStart(2,'0');
 return <>
 <section className="hero"><div className="wrap hero-grid"><div><div className="eyebrow">بِسْمِ اللَّهِ الرَّحْمَنِ الرَّحِيمِ</div><h1>زاد المسلم</h1><h2>رفيقك اليومي للقرآن والذكر والعبادة.</h2><p>منصة إسلامية متكاملة للقراءة والاستماع والذكر ومتابعة الصلاة، مصممة لتعمل على الكمبيوتر والموبايل.</p><div className="search"><input value={q} onChange={e=>setQ(e.target.value)} onKeyDown={e=>e.key==='Enter'&&(location.href=`/quran?search=${encodeURIComponent(q.trim())}`)} placeholder="ابحث في القرآن..."/><button className="btn" onClick={()=>location.href=`/quran?search=${encodeURIComponent(q.trim())}`}>بحث</button></div></div><div className="ayah"><div className="muted light">آية اليوم</div><div className="arabic">﴿ فَإِنَّ مَعَ الْعُسْرِ يُسْرًا ﴾</div><small>سورة الشرح · 5</small><Link className="light-link" href="/quran/94">فتح السورة ←</Link></div></div></section>
 <section className="section"><div className="wrap"><div className="prayer-next card"><div><div className="eyebrow">🕌 الصلاة القادمة</div><h2>{upcoming?.name||'الصلاة القادمة'}</h2><span className="muted">متبقي على الصلاة</span></div><div className="countdown">{fmt(hrs)}<span>:</span>{fmt(mins)}<span>:</span>{fmt(secs)}</div><div className="next-time">{upcoming?.time||'--:--'}</div></div></div></section>
 <section className="section"><div className="wrap"><div className="page-head"><div><h2>مواقيت الصلاة</h2><span className="muted">يتم تحديد الموقع من جهازك، مع القاهرة كخيار احتياطي.</span></div><Link className="chip" href="/prayer">التفاصيل ←</Link></div><div className="prayers six">{prayers.map(([a,b])=><div className="pray" key={a}><span>{a}</span><b>{p?.timings?.[b]||'--:--'}</b></div>)}</div></div></section>
 <section className="section"><div className="wrap"><div className="card home-daily"><div><div className="eyebrow">🌿 ميزة جديدة</div><h2>وردك اليوم + عندي دقيقة</h2><p className="muted">خطوات بسيطة تجمع وردك اليومي وتفيدك حتى لو معاك دقيقة واحدة.</p></div><Link className="btn" href="/daily">ابدأ وردك ←</Link></div></div></section><section className="section"><div className="wrap"><div className="grid quick">{quick.map(([icon,title,href])=><Link href={href} className="card quick-card" key={href}><span className="icon">{icon}</span><div><h3>{title}</h3><span className="muted">فتح القسم ←</span></div></Link>)}</div></div></section>
 <section className="section"><div className="wrap feature"><div className="card"><div className="eyebrow">حديث اليوم</div><h2>{h?.title||'حديث اليوم'}</h2><p className="arabic hadith-text">{h?.text||'إنما الأعمال بالنيات، وإنما لكل امرئ ما نوى.'}</p><small className="muted">{h?.source||'صحيح البخاري'}</small></div><div className="player"><div className="eyebrow light">التلاوة المميزة</div><div className="big">ياسر الدوسري</div><p>استمع مباشرة إلى سورة الفاتحة</p><audio controls preload="none" src="https://server11.mp3quran.net/yasser/001.mp3" style={{width:'100%'}}/><div className="actions"><Link className="btn" href="/audio">مركز التلاوات</Link><Link className="chip" href="/quran">فتح القرآن</Link></div></div></div></section>
 </>;
}
